RedmondTradeWork/Controllers/AdminController.cs
using RedmondTradeWork.Models.Entity;
using RedmondTradeWork.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedmondTradeWork.Controllers
{
    //  [Authorize]
    public class AdminController : BaseController
    {
        RedmondTradeDBEntities db = new RedmondTradeDBEntities();
        // GET: Admin
        public ActionResult Index()
        {


            var deger = db.TblMainPage.ToList();
            return View(deger);
        }



        [HttpGet]
        public ActionResult UpdateMainpage(int id)
        {
            var deger = db.TblMainPage.Find(id);
            return View("UpdateMainpage", deger);
        }

        [HttpPost]
        public ActionResult UpdateMainpages(TblMainPage t)
        {
            var main = db.TblMainPage.Find(t.ID);
            main.Title = t.Title;
            main.Description = t.Description;
            main.Photo1 = t.Photo1;
            main.İmage2 = t.İmage2;
            main.image3 = t.image3;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult AdminAbout()
        {
            var deger = db.TblAboutUs.ToList();
            return View(deger);
        }


        [HttpGet]
        public ActionResult UpdateAboutpage(int id)
        {
            var deger = db.TblAboutUs.Find(id);
            return View("UpdateAboutpage", deger);
        }

        [HttpPost]
        public ActionResult UpdateAboutpages(TblAboutUs t)
        {
            var about = db.TblAboutUs.Find(t.AboutUsID);
            about.Title = t.Title;
            about.Description = t.Description;
            about.SubHeadingTitle = t.SubHeadingTitle;
            about.SubHeading = t.SubHeading;
            about.Photo = t.Photo;
            about.Photo2 = t.Photo2;
            db.SaveChanges();
            return RedirectToAction("AdminAbout");

        }

        public ActionResult AdminSolutionPartners()
        {

            var deger = db.TblSolution_Partners.ToList();
            return View(deger);
        }


        [HttpGet]
        public ActionResult UpdateSolutionPage(int id)
        {
            var deger = db.TblSolution_Partners.Find(id);
            return View("UpdateSolutionPage", deger);
        }

        [HttpPost]
        public ActionResult UpdateSolutionPages(TblSolution_Partners t)
        {
            var spartner = db.TblSolution_Partners.Find(t.SolutionPartnersID);
            spartner.Title = t.Title;
            spartner.Description = t.Description;
            spartner.Description_En = t.Description_En;
            spartner.Description_Fr = t.Description_Fr;
            db.SaveChanges();
            return RedirectToAction("AdminSolutionPartners");
        }


        public ActionResult AdminWork()
        {
            var deger = db.TblWork.ToList();
            return View(deger);
        }

        [HttpGet]
        public ActionResult UpdateWorkPage(int id)
        {
            var deger = db.TblWork.Find(id);
            return View("UpdateWorkPage", deger);
        }
        [HttpPost]
        public ActionResult UpdateWorkPages(TblWork t)
        {
            var twork = db.TblWork.Find(t.WorkID);
            twork.Title = t.Title;
            twork.Title_En = t.Title_En;
            twork.Title_Fr = t.Title_Fr;
            twork.Description = t.Description;
            twork.Description_En = t.Description_En;
            twork.Description_Fr = t.Description_Fr;
            twork.Photo = t.Photo;
            db.SaveChanges();
            return RedirectToAction("AdminWork");
        }


        public ActionResult DeleteWork(int id)
        {
            var work = db.TblWork.Find(id);
            db.TblWork.Remove(work);
            db.SaveChanges();
            return RedirectToAction("AdminWork");
        }


        [HttpGet]
        public ActionResult InsertWork()
        {
            return View();
        }


        [HttpPost]
        public ActionResult InsertWork(TblWork t)
        {
            if (!ModelState.IsValid)
            {
                return View("InsertWork");
            }

            db.TblWork.Add(t);
            db.SaveChanges();
            return RedirectToAction("AdminWork");
        }


        public ActionResult AdminService()
        {
            var deger = db.TblService.ToList();
            return View(deger);
        }



        [HttpGet]
        public ActionResult UpdateServicePage(int id)
        {
            var deger = db.TblService.Find(id);
            return View("UpdateServicePage", deger);
        }

        [HttpPost]
        public ActionResult UpdateServicePages(TblService t)
        {
            var ServiceT = db.TblService.Find(t.ServiceID);
            ServiceT.Title = t.Title;
            ServiceT.Title_En = t.Title_En;
            ServiceT.Title_Fr = t.Title_Fr;
            ServiceT.Description = t.Description;
            ServiceT.Description_En = t.Description_En;
            ServiceT.Description_Fr = t.Description_Fr;
            ServiceT.İmage = t.İmage;
            ServiceT.ServiceIcon = t.ServiceIcon;
            db.SaveChanges();
            return RedirectToAction("AdminService");
        }


        public ActionResult DeleteService(int id)
        {
            var deger = db.TblService.Find(id);
            db.TblService.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("AdminService");
        }




        [HttpGet]
        public ActionResult InsertService()
        {
            return View();
        }


        [HttpPost]
        public ActionResult InsertService(TblService t)
        {
            if (!ModelState.IsValid)
            {
                return View("InsertService");
            }

            db.TblService.Add(t);
            db.SaveChanges();
            return RedirectToAction("AdminService");
        }





        public ActionResult AdminMessage()
        {
            var deger = db.TblMessage.ToList();
            return View(deger);
        }




        [HttpGet]
        public ActionResult AdminMessageDetailt(int id)
        {
            var deger = db.TblMessage.Find(id);
            return View(deger);
        }

        public ActionResult AdminMessageDelete(int id)
        {
            var deger = db.TblMessage.Find(id);
            db.TblMessage.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("AdminMessage");

        }

        public ActionResult AdminRole()
        {
            var values = db.TblAdmin.Where(x => x.Rol == "member").ToList();
            return View(values);
        }


        [HttpGet]
        public ActionResult UpdateRole(int id)
        {
            var value = db.TblAdmin.Find(id);
            return View("UpdateRole", value);
        }

        [HttpPost]
        public ActionResult UpdateRoles(TblAdmin t)
        {
            var value = db.TblAdmin.Find(t.ID);
            value.Name = t.Name;
            value.Password = t.Password;
            db.SaveChanges();
            return RedirectToAction("AdminRole");
        }

        public ActionResult DeleteRole(int id)
        {
            var values = db.TblAdmin.Find(id);
            db.TblAdmin.Remove(values);
            db.SaveChanges();
            return RedirectToAction("AdminRole");
        }


        [HttpGet]
        public ActionResult InsertRole()
        {
            return View();
        }


        [HttpPost]
        public ActionResult InsertRole(TblAdmin t)
        {
            if (!ModelState.IsValid)
            {
                return View("InsertRole");
            }
            t.Rol = "member";
            db.TblAdmin.Add(t);
            db.SaveChanges();
            return RedirectToAction("AdminRole");
        }




        public ActionResult AdminSearch(string search)
        {

            /* using (var db = new RedmondTradeDBEntities())
             {
                 var aranacak = db.TblContainer.AsQueryable();

                 aranacak = aranacak.Where(x => x.Durum == true);
                 // Arama parametresi boş değilse filtre uygula
                 if (!string.IsNullOrEmpty(search))
                 {
                     aranacak = aranacak.Where(x => x.ContainerNo.Contains(search) ||
                                                        x.Short_Content.Contains(search) ||
                                                        x.Deportune_Port.Contains(search) ||
                                                         x.Date.ToString().Contains(search) ||
                                                        x.Kim.Contains(search));
                 }

                 return View(aranacak.ToList());

                // var values = db.TblContainer.Where(x => x.Durum == true).ToList();

                 // return View(values); 
             }*/

            using (var db = new RedmondTradeDBEntities())
            {
                var query = db.TblContainer.AsQueryable();

                // Arama parametresi boş değilse
                if (!string.IsNullOrEmpty(search))
                {
                    // TblContainerContents tablosunda arama yap
                    var containerIds = db.TblContainerContents
                                         .Where(c => c.Product.Contains(search) ||
                                         c.TblContainer.Date.ToString().Contains(search) ||
                                         c.TblContainer.Short_Content.Contains(search) ||
                                         c.TblContainer.ContainerNo.Contains(search) ||
                                         c.TblContainer.Deportune_Port.Contains(search) ||
                                         c.TblContainer.Kim.Contains(search)

                                         ) // Burada Content alanında arama yapıyorsunuz

RedmondTradeWork/Controllers/MemberController.cs
using RedmondTradeWork.Models.Entity;
using RedmondTradeWork.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedmondTradeWork.Controllers
{
    public class MemberController : BaseController
    {
        RedmondTradeDBEntities db = new RedmondTradeDBEntities();
        // GET: Member
        public ActionResult Search(string search)
        {
            if (Session["UserRole"].ToString() != "admin")
            {
                Session["UserRole"] = "member";
            }

            using (var db = new RedmondTradeDBEntities())
            {
                var query = db.TblContainer.AsQueryable();

                // Arama parametresi boş değilse
                if (!string.IsNullOrEmpty(search))
                {
                    // TblContainerContents tablosunda arama yap
                    var containerIds = db.TblContainerContents
                                         .Where(c => c.Product.Contains(search) ||
                                         c.TblContainer.Date.ToString().Contains(search) ||
                                         c.TblContainer.Short_Content.Contains(search) ||
                                         c.TblContainer.ContainerNo.Contains(search) ||
                                         c.TblContainer.Deportune_Port.Contains(search) ||
                                         c.TblContainer.Kim.Contains(search)

                                         ) // Burada Content alanında arama yapıyorsunuz
                                         .Select(c => c.Container)            // ContainerID'leri çek
                                         .ToList();

                    // TblContainer'da ContainerID'lerine göre filtrele
                    query = query.Where(x => x.Durum == true && containerIds.Contains(x.ID));
                }
                else
                {
                    query = query.Where(x => x.Durum == true).OrderByDescending(x => x.ID);
                }




                return View(query.ToList());
            }
        }



        [HttpGet]
        public ActionResult SearchDetails(int id, string srch)
        {
            if (Session["UserRole"].ToString() != "admin")
            {
                Session["UserRole"] = "member";
            }

            var query = db.TblContainerContents.Where(x => x.TblContainer.ID == id);

            // Eğer arama terimi boş değilse, sorguyu filtrele
            if (!string.IsNullOrEmpty(srch))
            {
                query = query.Where(x =>
                    x.Unit.Contains(srch) ||
                    x.Quantity.ToString().Contains(srch) ||
                    x.TblContainer.Deportune_Port.Contains(srch) ||

                    x.Product.Contains(srch) ||
                    x.Nots.Contains(srch) ||
                    x.BuyerCompany.Contains(srch)); // Burada arama yapılacak sütunları belirtiyoruz
            }

            var values = query.Select(x => new ContainerDetailsViewModel
            {
                ID = x.ID,
                ContainerNo = x.TblContainer.ContainerNo,
                Product = x.Product,
                Unit = x.Unit,
                Quantity = x.Quantity,
                BuyerCompany = x.BuyerCompany,
                Date = x.TblContainer.Date,
                DeportunePort = x.TblContainer.Deportune_Port,
                Nots = x.Nots
            }).ToList();

            ViewBag.ContID = id;
            // Arama terimini View'a geri göndermek için

            return View(values);



        }


    }
}

RedmondTradeWork/Views/Member/Search.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblContainer>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Member/_MemberLayout - .cshtml";
}

<h2>Search</h2>



<br />
<br />

@using (Html.BeginForm("Search", "Member", FormMethod.Get))
{
    <div class="input-group mb-3">
        @Html.TextBox("search", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "search..." }) &ensp;

        <button type="submit" class="btn btn-warning">Search</button>
    </div>
}






<a href="https://www.searates.com/tr/container/tracking/" class="btn  btn-outline-danger" target="_blank">Tracking</a>
<br />
<br />

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Short Content</th>
        <th>Container No</th>
        <th>Date</th>
        <th>Deportune Port</th>
        <th>Who</th>
        <th>View</th>
     

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <th>@x.ID</th>
            <td>@x.Short_Content</td>
            <td style="display: flex; justify-content: space-between; align-items: center;">
                @x.ContainerNo
                <button class="btn btn-sm btn-outline-primary" onclick="copyToClipboard('@x.ContainerNo')">
                    <i class="fa fa-copy"></i>
                </button>

            </td>
            <td>@x.Date.Value.ToString("dd-MMM-yyyy")</td>
            <td>@x.Deportune_Port</td>
            <td>@x.Kim</td>



            <td><a href="/Member/SearchDetails/@x.ID" class="btn mb-1 btn-rounded btn-outline-dark">Detail</a></td>
       

        </tr>

    }
</table>

<script>
    function copyToClipboard(text) {
        navigator.clipboard.writeText(text).then(function () {
            alert("Kopyalandı: " + text);
        }).catch(function (err) {
            alert("Kopyalama başarısız oldu: " + err);
        });
    }
</script>

RedmondTradeWork/Views/Member/SearchDetails.cshtml
@using RedmondTradeWork.Models.Entity;
@model  List<RedmondTradeWork.ViewModels.ContainerDetailsViewModel>
@{
    ViewBag.Title = "SearchDetails";
    Layout = "~/Views/Member/_MemberLayout - .cshtml";
}

<h2>SearchDetails</h2>



@using (Html.BeginForm("SearchDetails", "Member", FormMethod.Get))
{
    <div class="input-group mb-3">
        @Html.TextBox("srch", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Search..." }) &ensp;

        <button type="submit" class="btn btn-warning">Search</button>
    </div>
}


<a href="/Member/Search/" class="btn mb-1 btn-rounded btn-outline-warning">Come Back</a> &ensp;



<br />
<br />

<table class="table table-bordered">
    <tr>

        <th>Container No</th>
        <th>Product</th>
        <th>Unit</th>
        <th>Quantity</th>
        <th>Buyer Company</th>
        <th>Date</th>
        <th>Deport Port</th>
        <th>Nots</th>


    </tr>
    @foreach (var x in Model)
    {
        <tr>


            <td>@x.ContainerNo</td>
            <td>@x.Product</td>
            <td>@x.Unit</td>
            <td>@x.Quantity</td>
            <td>@x.BuyerCompany</td>
            <td>@x.Date.Value.ToString("dd-MMM-yyyy")</td>
            <td>@x.DeportunePort</td>
            <td>@x.Nots</td>







        </tr>

    }
</table>

RedmondTradeWork/Views/Member/_MemberLayout - .cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

 @Html.Action("HeadPartial" , "Admin")

<body>

    @Html.Action("PreloaderPartial", "Admin")

    <div id="main-wrapper">


        @Html.Action("NavHeaderPartial", "Admin")


        @Html.Action("HeaderPartial", "Admin")


        @Html.Action("SideBarPartialMember", "Admin")


        <div class="content-body">




            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <p>@RenderBody()</p>
                                <br />

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>

        @Html.Action("FooterPartial", "Admin")
    </div>

    @Html.Action("ScriptPartial", "Admin")
</body>

</html>