RedmondTradeWork/Controllers/HomeFrController.cs
using MailKit.Net.Smtp;
using MimeKit;
using RedmondTradeWork.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedmondTradeWork.Controllers
{
  //  [AllowAnonymous]
    public class HomeFrController : Controller
    {
        RedmondTradeDBEntities db = new RedmondTradeDBEntities();
        // GET: HomeFr
        public ActionResult Index()
        {
            var deger = db.TblMainPage.Where(x => x.ID == 3).ToList();
            return View(deger);
        }
      

        public PartialViewResult MainAbaoutUsPartialFr()
        {
            var deger = db.TblAboutUs.Where(x => x.Langueage == "Fr").ToList();
            return PartialView(deger);
        }

        public PartialViewResult MainSolutionPartnersFr()
        {
            var deger = db.TblSolution_Partners.ToList();
            return PartialView(deger);
        }

        public PartialViewResult MainServiceFr()
        {
            var deger = db.TblService.ToList();
            return PartialView(deger);
        }

        public ActionResult SurNous()
        {
            var deger = db.TblAboutUs.Where(x => x.AboutUsID == 3).ToList();

            return View(deger);
        }


        public ActionResult Service()
        {
            var deger = db.TblWork.ToList();
            return View(deger);
        }

        [HttpGet]
        public ActionResult Contact()
        {


            return View();
        }

        [HttpPost]
        public ActionResult Contact(TblMessage t)
        {
            MimeMessage mimeMessage = new MimeMessage();

            MailboxAddress mailboxAddress = new MailboxAddress(t.Name, t.Email);
            mimeMessage.From.Add(mailboxAddress); // mesaj kimden 

            MailboxAddress mailboxAddressTo = new MailboxAddress("User", "berkanburakturgut@gmail.com" /* kime */);
            mimeMessage.To.Add(mailboxAddressTo); // mesaj kime 

            var bodyBuilder = new BodyBuilder();
            bodyBuilder.TextBody = t.Message + " \n \nSender : " + t.Email; // mesajın içerik ne 
            mimeMessage.Body = bodyBuilder.ToMessageBody();

            mimeMessage.Subject = t.Title;

            SmtpClient client = new SmtpClient();
            client.Connect("smtp.gmail.com", 587, false); // 587 port numarası , ssl gereksin mi = fasle istersen true yaparsın
            client.Authenticate("berkanburakturgut@gmail.com", "fwsdhhdhrzzhgqmq");
            client.Send(mimeMessage);
            client.Disconnect(true);



            //t.Email = "admin@gmail.com";
            //t.Name= "admin";
            t.Date = DateTime.Parse(DateTime.Now.ToShortDateString());


            db.TblMessage.Add(t);
            db.SaveChanges();

            return RedirectToAction("Contact");
        }
    }
}

RedmondTradeWork/Views/HomeFr/Contact.cshtml
@model RedmondTradeWork.Models.Entity.TblMessage

@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout - Fr.cshtml";
}



<!-- Page Title -->
<div class="page-title light-background">
    <div class="container">
        <h1 style="color: #8e0723 !important">Contact</h1>
        <nav class="breadcrumbs">
            <ol>
                <li><a href="Index">Accueil</a></li>
                <li class="current">Contact</li>
            </ol>
        </nav>
    </div>
</div><!-- End Page Title -->
<br />
<br />






<!-- Contact Section -->
<section id="contact" class="contact section">

    <div class="container" data-aos="fade">

        <div class="row gy-5 gx-lg-5">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5344.6461072368975!2d38.79828897455717!3d37.201521786676956!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15347a98a46390a9%3A0xaa26baaacdc26bbf!2zWWVsa2VuJ3MgdG93ZXJzIEthcmFhxJ9hw6cgaW7Fnw!5e0!3m2!1str!2str!4v1733334253019!5m2!1str!2str" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


            <br />

            <div class="col-lg-4">

                <div class="info">
                    <h3 style="color: #8e0723 !important">Contactez-nous</h3>
                    <p>Nous vous accueillons dans notre bureau pour discuter d’autres problématiques.</p>

                    <div class="info-item d-flex">
                        <i class="bi bi-geo-alt flex-shrink-0"></i>
                        <div>
                            <h4 style="color: #8e0723 !important">emplacement:</h4>
                            <p>
                                Yelken Towers Sitesi B Blok No.1 <br />
                                Karakopru/Sanliurfa
                            </p>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="info-item d-flex">
                        <i class="bi bi-envelope flex-shrink-0"></i>
                        <div>
                            <h4 style="color: #8e0723 !important">Email:</h4>
                            <p>info@redmondtrade.com</p>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="info-item d-flex">
                        <i class="bi bi-whatsapp flex-shrink-0"></i>
                        <div>
                            <h4 style="color: #8e0723 !important">Téléphone:</h4>
                            <p><a href="https://wa.me/905346500543" target="_blank" style="color:rgb(128 128 128)">+90 534 650 05 43</a> </p>
                        </div>
                    </div><!-- End Info Item -->

                </div>

            </div>

            <div class="col-lg-8">
                <form action="Contact" method="post" class="php-email-form">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            @Html.TextBoxFor(x => x.Name, new { @type = "text", @class = "form-control", placeholder = "ton nom", requried = "" })

                        </div>
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            @Html.TextBoxFor(x => x.Email, new { @type = "email", @class = "form-control", placeholder = "votre nom de famille", requried = "" })

                        </div>
                    </div>
                    <div class="form-group mt-3">
                        @Html.TextBoxFor(x => x.Title, new { @type = "text", @class = "form-control", placeholder = "Titre", requried = "" })

                    </div>
                    <div class="form-group mt-3">
                        @Html.TextAreaFor(x => x.Message, new { @class = "form-control", placeholder = "Sujet", requried = "" })

                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">Envoyer un message</button></div>
                </form>
            </div><!-- End Contact Form -->

        </div>

    </div>

</section>

<!-- /Contact Section -->

RedmondTradeWork/Views/HomeFr/Index.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblMainPage>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout - Fr.cshtml";
}

<!-- About Section -->
<section id="about" class="about section">
    <div class="container">
        <div class="row align-items-center justify-content-between">
            <div class="col-lg-7 mb-5 mb-lg-0 order-lg-2" data-aos="fade-up" data-aos-delay="400">
                <div class="swiper init-swiper">
                    <script type="application/json" class="swiper-config">
                        {
                          "loop": true,
                          "speed": 600,
                          "autoplay": {
                            "delay": 5000
                          },
                          "slidesPerView": "auto",
                          "pagination": {
                            "el": ".swiper-pagination",
                            "type": "bullets",
                            "clickable": true
                          },
                          "breakpoints": {
                            "320": {
                              "slidesPerView": 1,
                              "spaceBetween": 40
                            },
                            "1200": {
                              "slidesPerView": 1,
                              "spaceBetween": 1
                            }
                          }
                        }
                    </script>
                    @foreach (var x in Model)
                    {
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <img src="@x.Photo1" alt="Image" class="img-fluid">
                            </div>
                            <div class="swiper-slide">
                                <img src="@x.İmage2" alt="Image" class="img-fluid">
                            </div>
                            <div class="swiper-slide">
                                <img src="@x.image3" alt="Image" class="img-fluid">
                            </div>
                        </div>}

                    <div class="swiper-pagination"></div>
                </div>
            </div>
            <div class="col-lg-4 order-lg-1">
                <span class="section-subtitle" data-aos="fade-up">ACCUEILLIR!!</span>
                @foreach (var x in Model)
                {
                    <h1 class="mb-4" data-aos="fade-up">
                        @x.Title
                    </h1>
                    <p data-aos="fade-up">
                        @x.Description
                    </p>}
                <p class="mt-5" data-aos="fade-up">
                    <a href="/HomeFr/Service" class="btn btn-danger">services</a>
                </p>

            </div>
        </div>
    </div>
</section>
<!-- /About Section -->
<!-- About 2 Section -->
@Html.Action("MainAbaoutUsPartialFr", "HomeFr")
<!-- /About 2 Section -->
<!-- Services Section -->
<section id="services" class="services section light-background">
</section>
<!-- /Services Section -->
<!-- Blog Posts Section -->
@Html.Action("MainSolutionPartnersFr", "HomeFr")
<!-- /Blog Posts Section -->
<!-- Tabs Section -->
@Html.Action("MainServiceFr", "HomeFr")
<!-- /Tabs Section -->

RedmondTradeWork/Views/HomeFr/MainAbaoutUsPartialFr.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblAboutUs>

<section id="about-2" class="about-2 section light-background">
    @foreach (var x in Model)
    {
<div class="container">
    <div class="content">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-5 col-lg-4 col-xl-4 order-lg-2 offset-xl-1 mb-4">
                <div class="img-wrap text-center text-md-left" data-aos="fade-up" data-aos-delay="100">
                    <div class="img">
                        <img src="@x.Photo" alt="circle image" class="img-fluid">
                    </div>
                </div>
            </div>

            <div class="offset-md-0 offset-lg-1 col-sm-12 col-md-5 col-lg-5 col-xl-4" data-aos="fade-up">
                <div class="px-3">
                    <span class="content-subtitle">Notre mission</span>
                    <h2 class="content-title text-start">
                        @x.Title
                    </h2>
                    <p class="lead">
                        @x.Description
                    </p>

                    <p>
                        <a href="/HomeFr/SurNous" class="btn btn-outline-danger" style="color:#8e0723 !important">sur nous</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>}
</section>

RedmondTradeWork/Views/HomeFr/MainServiceFr.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblService>


<section id="tabs" class="tabs section light-background">

    <div class="container">

        <div class="row gap-x-lg-4 justify-content-between">

            <div class="col-lg-4 js-custom-dots">
                <!-- /.service -->
                @foreach (var x in Model)
                {
    <a href="#" class="service-item link horizontal d-flex active" data-aos="fade-left" data-aos-delay="0">
        <div class="service-icon color-1 mb-4">
            <i class="@x.ServiceIcon"></i>

        </div>
        <!-- /.icon -->
        <div class="service-contents">
            <h3>@x.Title_Fr</h3>
            <p>
                @x.Description_Fr
            </p>
        </div>
        <!-- /.service-contents-->
    </a> <!-- /.service -->}
            </div>

            <div class="col-lg-8">

                <div class="swiper init-swiper-tabs">

                    <script type="application/json" class="swiper-config">
                        {
                          "loop": true,
                          "speed": 600,
                          "autoHeight": true,
                          "autoplay": {
                            "delay": 5000
                          },
                          "slidesPerView": "auto",
                          "pagination": {
                            "el": ".swiper-pagination",
                            "type": "bullets",
                            "clickable": true
                          },
                          "breakpoints": {
                            "320": {
                              "slidesPerView": 1,
                              "spaceBetween": 40
                            },
                            "1200": {
                              "slidesPerView": 1,
                              "spaceBetween": 1
                            }
                          }
                        }
                    </script>

                    <div class="swiper-wrapper">
                        @foreach (var x in Model)
                        {
            <div class="swiper-slide">
                <img src="@x.İmage" alt="Image" class="img-fluid">

            </div>}



                    </div>
                </div>


            </div>


        </div>


    </div>
</section>

RedmondTradeWork/Views/HomeFr/MainSolutionPartnersFr.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblSolution_Partners>

<section id="blog-posts" class="blog-posts section">
    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">

        <h2>Nos partenaires solutions</h2>
    </div><!-- End Section Title -->




    <div class="container">

        <div class="row gy-4">
            @foreach (var x in Model)
            {
<div class="col-md-6 col-lg-4">



    <div class="post-entry" data-aos="fade-up" data-aos-delay="100">
        <a href="#" class="thumb d-block"><img src="@x.Photo" alt="Image" class="img-fluid rounded"></a>

        <div class="post-content">

            <h3><a href="#">@x.Title</a></h3>
            <p>
                @x.Description_Fr
            </p>


        </div>
    </div>

</div>            }
        </div>

    </div>


</section>

RedmondTradeWork/Views/HomeFr/Service.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblWork>

@{
    ViewBag.Title = "Service";
    Layout = "~/Views/Shared/_Layout - Fr.cshtml";
}





<!-- Page Title -->
<div class="page-title light-background">
    <div class="container">
        <h1 style="color: #8e0723 !important">Service</h1>
        <nav class="breadcrumbs">
            <ol>
                <li><a href="Index">Accueil</a></li>
                <li class="current">Service</li>
            </ol>
        </nav>
    </div>
</div><!-- End Page Title -->
<br />
<br />


@foreach (var x in Model.OrderBy(x => x.WorkID))
{
    if (x.WorkID % 2 != 0)
    {
        <div class="about wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-5 col-md-6">
                        <div class="about-img">
                            <img src="@x.Photo" alt="Image">
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-6">
                        <div class="section-header text-left">

                            <h2 style="color: #8e0723">@x.Title_Fr</h2>
                        </div>
                        <div class="about-text">
                            <p style="font: 20px 'playfair display', serif;">
                                @x.Description_Fr
                            </p>


                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
    }


    else if (x.WorkID % 2 == 0)
    {
        <br />
        <div class="about wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-lg-7 col-md-6">
                        <div class="section-header text-left">

                            <h2 style="color: #8e0723">@x.Title_Fr</h2>
                        </div>
                        <div class="about-text">
                            <p style="font: 20px 'playfair display', serif;">
                                @x.Description_Fr
                            </p>


                        </div>
                    </div>

                    <div class="col-lg-5 col-md-6">
                        <div class="about-img">
                            <img src="@x.Photo" alt="Image">
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <br />
    }


}
<br />
<br /> 

RedmondTradeWork/Views/HomeFr/SurNous.cshtml
@using RedmondTradeWork.Models.Entity;
@model List<TblAboutUs>

@{
    ViewBag.Title = "SurNous";
    Layout = "~/Views/Shared/_Layout - Fr.cshtml";
}





<!-- Page Title -->
<div class="page-title light-background">
    <div class="container">
        <h1 style="color: #8e0723 !important">Sur Nous</h1>
        <nav class="breadcrumbs">
            <ol>
                <li><a href="Index">Accueil</a></li>
                <li class="current">Sur Nous</li>
            </ol>
        </nav>
    </div>
</div><!-- End Page Title -->
@foreach (var x in Model)
{<!-- About 2 Section -->
    <section id="about-2" class="about-2 section">

        <div class="container">
            <div class="content">
                <div class="row justify-content-center">
                    <div class="col-sm-12 col-md-5 col-lg-4 col-xl-4 order-lg-2 offset-xl-1 mb-4">
                        <div class="img-wrap text-center text-md-left" data-aos="fade-up" data-aos-delay="100">
                            <div class="img">
                                <img src="@x.Photo" alt="circle image" class="img-fluid">
                            </div>
                        </div>
                    </div>

                    <div class="offset-md-0 offset-lg-1 col-sm-12 col-md-5 col-lg-5 col-xl-4" data-aos="fade-up">
                        <div class="px-3">
                            <span class="content-subtitle">Notre Mission</span>
                            <h2 class="content-title text-start">
                                @x.Title
                            </h2>
                            <p class="lead">
                                @x.Description
                            </p>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- /About 2 Section --> <!-- Stats Section -->
    <section id="stats" class="stats section light-background">

        <div class="container">

            <div class="row gy-4 justify-content-center">

                <div class="col-lg-5">
                    <div class="images-overlap">
                        <img src="@x.Photo2" alt="student" class="img-fluid img-1" data-aos="fade-up">
                    </div>
                </div>

                <div class="col-lg-4 ps-lg-5">

                    <h2 class="content-title">@x.SubHeadingTitle</h2>
                    <p class="lead">
                        @x.SubHeading
                    </p>


                </div>

            </div>

        </div>
    </section> <!-- /Stats Section -->}